changes to add hana_role attribute during probe
SUSE/SAPHanaSR pull request #128
Opened 2022-10-04 18:27 UTC by sairamgopal

Added a check to identify the status of the primary node and set the "hana__roles" attribute during probe, then when cluster is removed from the maintenance, cluster will not try to stop and start the DB or to trigger a failover as it will see the operational primary node during the probe.

2022-10-04 18:28 UTC, sairamgopal commented
Hi @PeterPitterling,
As you suggested I closed old PR and created a new one. Thank you

2022-10-29 09:44 UTC, sairamgopal commented
Hi @fmherschel @angelabriel could you please review this PR. 

When we put cluster in maintenance mode and stop pacemaker service then after starting the pacemaker service again a probe will be triggered to check the current status of all the resources, but cluster will not perform any action to start or stop the resources as the cluster is still in maintenance mode. 

But the current resource agents check and set only the hana version but not checking the hsr status to set the hana_roles attribute during the probe, due to this when cluster is removed from maintenance mode after pacemaker/ cluster service start, cluster is stopping and starting the DB on primary node (which leads to an unexpected downtime).

Inorder to avoid this situation what suse suggested (`case 00360697`) is to follow different procedure ie we only need to put master slave resource and Ip resources to maintenance mode then after pacemaker service restart we need to remove master slave and ip resources from the maintenance mode. But this works only for pacemaker 2.0 version. 

On Pacemaker 1.1 (SLES12 SP4) these steps will not work because we cannot restart pacemaker service by only putting few resources to maintenance mode. (either, we need to put entire cluster to maintenance, or it should not be in maintenance), So we need to follow different procedure for this.  Having different procedure/steps for different versions of pacemaker can lead to handling error.

So, if we include a step to check HSR status and set hana_role attribute during the probe then the issue will be fixed, and we can have a common procedure for both pacemaker versions also.

2022-10-31 14:14 UTC, fmherschel requested changes
This PR needs to be rejected. SAPHana must not change the attribute `hana_${sid}_roles`. If you check the current master branch SAPHana only "gets" this attribute but does not "set" it. 
`hana_${sid}_roles` must only be set by SAPHanaTopology.
This is also why we define to set the multi-state (SAPHana) resource to maintenance and keep the normal clone (SAPHanaTopology) active.

2022-10-31 14:19 UTC, sairamgopal commented
I am not exactly sure why that is not working on Pacemaker 1.1.19+20181105.ccd6b5b10-3.31.1-1.1.19+20181105.ccd6b5b10 on SLES12SP4, but same has been confirmed by SUSE Support team and suggested to use a different procedure for pacemaker 1.1 on SLES12SP4. 

```
The L2 did the lab and confirmed you have to run different procedures between pacemaker 1 vs 2. So for pacemaker 1 you have to follow the steps on https://github.com/SUSE/SAPHanaSR/blob/master/man/SAPHanaSR_maintenance_examples.7

And for pacemaker 2 https://www.suse.com/c/sles-for-sap-os-patching-procedure-for-scale-up-perf-opt-hana-cluster/#two
```

2022-10-31 14:43 UTC, fmherschel commented
I close this PR as it will create more problems.

2022-10-31 14:43 UTC, closed without merging

2022-10-31 14:43 UTC, sairamgopal commented
```
This PR needs to be rejected. SAPHana must not change the attribute hana_${sid}_roles. If you check the current master branch SAPHana only "gets" this attribute but does not "set" it.
hana_${sid}_roles must only be set by SAPHanaTopology.
```

Thanks for the update @fmherschel, 
During the probe SAP Hana Resource agents must check the current HSR status and set the hana_${sid}_roles attribute right ? but that is not happening with the current resource agents. I am not sure why SAPHana must not change the attribute hana_${sid}_roles, at first I tried to include the check in SAPHanaTopology Resource agent during the probe but that didnt help to fix the issue, so I included the code to SAPHana . I will double check the code to include that in the SAPHanaTopology Resource agent.

2022-10-31 16:11 UTC, fmherschel commented
@sairamgopal Please also do not change SAPHanaTopology.

2022-10-31 16:12 UTC, fmherschel commented
We try to reproduce the issue and typically the maintenance procedure needs to be checked. This is not a bug of the RA.

2022-10-31 16:26 UTC, sairamgopal commented
Sure, will wait for your update.

We are facing issue with the below procedure on pacemaker 1.1 SLES 12 SPS04

```
1. put msl_resource to maintenance mode
2. put ip resource to maintenance mode
3. stop the cluster using crm cluster stop
4. Perform the required task
5. start the cluster using crm cluster start
6. Remove msl_resource from maintenance mode
7. Remove Ip resource from maintenance mode.
```

our concern is having different procedures for different pacemaker versions can lead to handling errors.
It will be good if a single working maintenance procedure for all pacemaker versions.

2022-10-31 16:52 UTC, fmherschel commented
> ramsau2:/var/lib/rmt # # rmt-cli repos list --all | egrep '(SLE-12-SP4-SAP-Update.*12-x86_64|SLE-HA12-SP4-Updates.*12-x86_64|SLES12-SP4-Updates.*12-x86_64)' ramsau2:/var/lib/rmt # # 3154 2819 2769 

This is why we try to reproduce first the issue.
SLE12SP4 is already on pacemaker 1.1.x which is neither 1.0 not 2.0. So I doublecheck about the differences between 1.1.x and 2.0.

2022-11-02 09:34 UTC, fmherschel commented
@sairamgopal : We have set-up a cluster with SLE12SP4 code base. This cluster has pacemaker 1.1.19. With this cluster the maintenance procedure for pacemaker 2.0 works out of the box.
With that neither the PR not a change of teh maintenance procedure is needed any more.

2022-11-02 09:46 UTC, sairamgopal commented
Thanks for the update @fmherschel, not sure why that is not working on all our cluster having pacemaker 1.1.19 also on the cluster where Suse engineer performed the tests and confirmed that the maintenance procedure for pacemaker 2.0 is not working on pacemaker 1.1.19 and suggested to follow the different procedure for that. (https://scc.suse.com/support/cases/00360697)

if possible, could you please share us the test results or steps that you performed on the cluster.