Angi devel to be merged into main
SUSE/SAPHanaSR pull request #251
Opened 2024-04-10 10:22 UTC by fmherschel

Upgrade to 1.2.6

2024-04-10 17:56 UTC, angelabriel requested changes
Looks good to me. Only 2 typos in the date of 2 man pages found.  Would be nice if that can be fixed before we merge. 
And the script `tools/SAPHanaSR-upgrade-to-angi-demo` needs some love to pass the **shellcheck** (or simply exclude this file from the check for now)
Thanks

2024-04-10 17:56 UTC, angelabriel commented on man-tester/SAPHanaSR-testCluster.8
> +(c) 2023-2014 SUSE LLC
Typo 2014 --> 2024

2024-04-10 17:56 UTC, angelabriel commented on man/SAPHanaSR_maintenance_examples.7
> +.TH SAPHanaSR_maintenance_examples 7 "25 Jan 2023" "" "SAPHanaSR"
Typo in the year --> 2024

2024-04-11 06:52 UTC, fmherschel commented on man-tester/SAPHanaSR-testCluster.8
> +(c) 2023-2014 SUSE LLC
DONE

2024-04-11 06:52 UTC, fmherschel commented on man/SAPHanaSR_maintenance_examples.7
> +.TH SAPHanaSR_maintenance_examples 7 "25 Jan 2023" "" "SAPHanaSR"
DONE

2024-04-11 07:34 UTC, angelabriel commented on man-tester/SAPHanaSR-testCluster.8
> +(c) 2023-2014 SUSE LLC
Thanks

2024-04-11 07:34 UTC, angelabriel commented on man/SAPHanaSR_maintenance_examples.7
> +.TH SAPHanaSR_maintenance_examples 7 "25 Jan 2023" "" "SAPHanaSR"
Thanks

2024-04-11 08:51 UTC, fmherschel commented
Also shellcheck should be satisfied now.

2024-04-11 09:14 UTC, merged